import React, { useState, useEffect } from 'react';
import { 
  Check, 
  Copy, 
  Layers, 
  Code2, 
  GitFork, 
  Calendar, 
  AlertTriangle, 
  ExternalLink, 
  Download, 
  Sparkles, 
  Zap, 
  ShieldCheck, 
  TrendingDown, 
  Lightbulb, 
  Plus, 
  ArrowRight,
  Bookmark,
  BookmarkCheck,
  Sliders,
  Scale,
  CheckCircle2,
  Cpu,
  Star
} from 'lucide-react';
import { 
  ResearchSolution, 
  ProjectSuggestion, 
  ResearchConstraints,
  generateProjectRecommendations, 
  saveBlueprintToStorage,
  getSavedBlueprints,
  switchSolutionApproach
} from '../../services/aiResearchService';
import { MultiLangCodeSandbox } from './MultiLangCodeSandbox';
import { SolutionComparisonMatrix } from './SolutionComparisonMatrix';
import { SlideUp } from '../common/MotionWrapper';
import { Badge } from '../common/Badge';

interface SolutionBlueprintViewProps {
  solution: ResearchSolution;
  onExploreTool?: (toolId: string) => void;
  onUpdateConstraints?: (constraints: Partial<ResearchConstraints>) => void;
}

export const SolutionBlueprintView: React.FC<SolutionBlueprintViewProps> = ({ 
  solution: propSolution,
  onExploreTool,
  onUpdateConstraints
}) => {
  const [activeSolution, setActiveSolution] = useState<ResearchSolution>(propSolution);
  const [activeTab, setActiveTab] = useState<'compare_solutions' | 'suggestions' | 'architecture' | 'stack' | 'roadmap' | 'starter_code' | 'tradeoffs'>('compare_solutions');
  const [copiedMarkdown, setCopiedMarkdown] = useState(false);
  const [copiedSuggestionId, setCopiedSuggestionId] = useState<string | null>(null);
  const [isSaved, setIsSaved] = useState(() => {
    return getSavedBlueprints().some(b => b.id === propSolution.id);
  });

  useEffect(() => {
    setActiveSolution(propSolution);
  }, [propSolution]);

  // Dynamic Constraints state
  const [showConstraints, setShowConstraints] = useState(false);
  const [privacy, setPrivacy] = useState<ResearchConstraints['privacyLevel']>(activeSolution.constraints?.privacyLevel || '100% Offline / Self-Hosted');
  const [scale, setScale] = useState<ResearchConstraints['projectScale']>(activeSolution.constraints?.projectScale || 'MVP (1-1,000 users)');
  const [platform, setPlatform] = useState<ResearchConstraints['targetPlatform']>(activeSolution.constraints?.targetPlatform || 'Web Application');

  // Suggestions state with support for generating more
  const [suggestionsList, setSuggestionsList] = useState<ProjectSuggestion[]>(activeSolution.suggestions || []);
  const [seedCount, setSeedCount] = useState(1);
  const [selectedCategoryFilter, setSelectedCategoryFilter] = useState<string>('all');

  const handleSelectApproach = (approachId: string) => {
    const updated = switchSolutionApproach(activeSolution, approachId);
    setActiveSolution(updated);
  };

  const handleGenerateMoreSuggestions = () => {
    const nextSeed = seedCount + 1;
    setSeedCount(nextSeed);
    const moreSuggestions = generateProjectRecommendations(
      { title: activeSolution.queryTitle || activeSolution.title, category: activeSolution.projectCategory || 'Technology' },
      activeSolution.queryTitle || activeSolution.title,
      nextSeed
    );
    // Merge new unique suggestions
    setSuggestionsList(prev => {
      const existingIds = new Set(prev.map(s => s.id));
      const filtered = moreSuggestions.filter(s => !existingIds.has(s.id));
      return [...prev, ...filtered];
    });
  };

  const handleSaveBlueprint = () => {
    saveBlueprintToStorage(activeSolution);
    setIsSaved(true);
    setTimeout(() => setIsSaved(false), 2500);
  };

  const handleCopySuggestion = (sug: ProjectSuggestion) => {
    const text = `[${sug.categoryLabel}] ${sug.title}\nImpact: ${sug.impact} | Effort: ${sug.effort}\n${sug.description}\nAction: ${sug.actionableStep}`;
    navigator.clipboard.writeText(text);
    setCopiedSuggestionId(sug.id);
    setTimeout(() => setCopiedSuggestionId(null), 2000);
  };

  const handleExportMarkdown = () => {
    const md = `# Solution Blueprint & Recommendations: ${activeSolution.queryTitle || activeSolution.title}
Generated by INNOVEXA AI Research Engine

## Executive Summary
${activeSolution.executiveSummary}

## Key Metrics
- Feasibility Score: ${activeSolution.feasibilityScore || 85}%
- Time to MVP: ${activeSolution.speedToMarketDays || 30} Days
- Estimated Cloud Cost: ${activeSolution.estimatedCloudCost || '$20/mo'}

## Related Solution Approaches (${activeSolution.relatedSolutions?.length || 0})
${activeSolution.relatedSolutions?.map(r => `### ${r.title} (${r.tag})
- **Strategy:** ${r.architectureSummary}
- **Core Stack:** ${r.coreStack?.join(', ')}
- **Speed to MVP:** ${r.speedToMarketDays} Days | **Cost:** ${r.estimatedCloudCost}
- **Pros:** ${r.pros?.join('; ')}
- **Cons:** ${r.cons?.join('; ')}`).join('\n\n')}

## Recommended Open Source Stack
${(activeSolution.openSourceStack || []).map((t: any) => `- **${t.name || t.toolName}** (${t.category}) - ${t.stars || ''} stars - License: ${t.license || 'MIT'}\n  ${t.description || t.reason}\n  Install: \`${t.installCommand || ''}\``).join('\n\n')}

## Architecture Layers
${(activeSolution.architecture || []).map((a: any) => `### ${a.layer}: ${a.component || a.name}\n- **Technology:** ${a.technology || (a.components && a.components.join(', '))}\n- **Role:** ${a.role || a.description}`).join('\n\n')}

## Implementation Roadmap
${(activeSolution.roadmap || []).map((r: any) => `### ${r.phase || r.phaseNumber}: ${r.title} (${r.duration})\n**Tasks:**\n${(r.tasks || []).map((t: any) => `- ${typeof t === 'string' ? t : t?.title || ''}`).join('\n')}\n**Deliverable:** ${r.deliverable || (r.deliverables && r.deliverables.join(', '))}`).join('\n\n')}
`;
    navigator.clipboard.writeText(md);
    setCopiedMarkdown(true);
    setTimeout(() => setCopiedMarkdown(false), 2200);
  };

  const filteredSuggestions = suggestionsList.filter(s => {
    if (selectedCategoryFilter === 'all') return true;
    return s.category === selectedCategoryFilter;
  });

  return (
    <div className="space-y-6">
      
      {/* Hero Overview Card */}
      <SlideUp delay={0.05}>
        <div className="bg-white rounded-3xl border border-[#E5E0D6] p-7 shadow-card space-y-6">
          <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6 pb-6 border-b border-[#E5E0D6]">
            <div className="space-y-2 max-w-2xl">
              <div className="flex items-center gap-2 flex-wrap">
                <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-[11px] font-mono font-bold bg-[#8875E8]/10 text-[#8875E8] border border-[#8875E8]/20">
                  <Sparkles className="w-3 h-3" />
                  AI RESEARCH BLUEPRINT
                </span>
                <Badge variant="mint">100% OPEN SOURCE</Badge>
                <span className="text-xs font-mono text-[#8E90A2]">
                  {activeSolution.projectCategory}
                </span>
              </div>
              <h2 className="font-serif text-2xl sm:text-3xl font-bold text-[#181924]">
                {activeSolution.queryTitle}
              </h2>
              <p className="text-xs sm:text-sm text-[#555768] leading-relaxed">
                {activeSolution.executiveSummary}
              </p>
            </div>

            {/* Quick Metrics */}
            <div className="grid grid-cols-3 gap-3 shrink-0 bg-[#F7F4EE] p-4 rounded-2xl border border-[#E5E0D6]">
              <div className="text-center px-2">
                <div className="font-serif text-3xl font-bold text-[#4FA89B]">
                  {activeSolution.feasibilityScore}%
                </div>
                <div className="text-[9px] font-mono font-bold uppercase text-[#8E90A2] mt-0.5">
                  FEASIBILITY
                </div>
              </div>
              <div className="text-center px-2 border-x border-[#E5E0D6]">
                <div className="font-serif text-3xl font-bold text-[#6875E8]">
                  {activeSolution.speedToMarketDays}d
                </div>
                <div className="text-[9px] font-mono font-bold uppercase text-[#8E90A2] mt-0.5">
                  TIME TO MVP
                </div>
              </div>
              <div className="text-center px-2">
                <div className="font-serif text-3xl font-bold text-[#E66F82]">
                  {(activeSolution.estimatedCloudCost || '$10').split(' ')[0] || '$10'}
                </div>
                <div className="text-[9px] font-mono font-bold uppercase text-[#8E90A2] mt-0.5">
                  MONTHLY COST
                </div>
              </div>
            </div>
          </div>

          {/* Quick Approach Switcher Strip */}
          {activeSolution.relatedSolutions && activeSolution.relatedSolutions.length > 0 && (
            <div className="p-3.5 bg-[#FAF8F5] rounded-2xl border border-[#EAE4D9] flex flex-col sm:flex-row sm:items-center justify-between gap-3">
              <div className="flex items-center gap-2">
                <Scale className="w-4 h-4 text-[#6875E8]" />
                <span className="font-mono text-xs font-bold text-[#181924]">
                  Active Solution Approach:
                </span>
              </div>

              <div className="flex items-center gap-1.5 overflow-x-auto pb-1 no-scrollbar">
                {activeSolution.relatedSolutions.map(appr => {
                  const isSelected = appr.id === activeSolution.activeApproachId;
                  return (
                    <button
                      key={appr.id}
                      onClick={() => handleSelectApproach(appr.id)}
                      className={`px-3 py-1.5 rounded-xl font-mono text-[11px] font-bold transition-all whitespace-nowrap flex items-center gap-1.5 ${
                        isSelected 
                          ? 'bg-[#181924] text-white shadow-sm' 
                          : 'bg-white text-[#555768] hover:text-[#181924] border border-[#E5E0D6]'
                      }`}
                    >
                      {isSelected && <Star className="w-3 h-3 fill-amber-400 text-amber-400" />}
                      <span>{appr.title}</span>
                    </button>
                  );
                })}
              </div>
            </div>
          )}

          {/* Plain-English Takeaways Box */}
          {activeSolution.keyTakeaways && activeSolution.keyTakeaways.length > 0 && (
            <div 
              className="p-5 rounded-2xl space-y-3"
              style={{
                background: 'linear-gradient(135deg, rgba(79,168,155,0.06) 0%, rgba(104,117,232,0.06) 100%)',
                border: '1px solid rgba(79,168,155,0.2)'
              }}
            >
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2 font-mono text-xs font-bold text-[#181924] uppercase tracking-wider">
                  <Sparkles className="w-4 h-4 text-[#4FA89B]" />
                  <span>Plain-English Research Takeaways</span>
                </div>
                <span className="text-[10px] font-mono text-[#4FA89B] font-bold">READY TO EXECUTE</span>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5 pt-1">
                {activeSolution.keyTakeaways.map((takeaway, idx) => (
                  <div key={idx} className="flex items-start gap-2 text-xs text-[#2B2C3C] leading-relaxed">
                    <CheckCircle2 className="w-4 h-4 text-[#4FA89B] shrink-0 mt-0.5" />
                    <span>{takeaway}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Action Row & Constraints Toggle */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pt-2">
            <div className="flex items-center gap-2">
              <button
                onClick={() => setShowConstraints(!showConstraints)}
                className="flex items-center gap-2 bg-[#F7F4EE] hover:bg-[#E5E0D6] text-[#181924] px-4 py-2 rounded-xl text-xs font-mono font-bold transition-all border border-[#E5E0D6]"
              >
                <Sliders className="w-3.5 h-3.5 text-[#6875E8]" />
                <span>{showConstraints ? 'Hide Constraints' : 'Adjust Research Parameters'}</span>
              </button>

              <button
                onClick={handleSaveBlueprint}
                className="flex items-center gap-2 bg-[#F7F4EE] hover:bg-[#E5E0D6] text-[#181924] px-4 py-2 rounded-xl text-xs font-mono font-bold transition-all border border-[#E5E0D6]"
              >
                {isSaved ? <BookmarkCheck className="w-3.5 h-3.5 text-[#4FA89B]" /> : <Bookmark className="w-3.5 h-3.5" />}
                <span>{isSaved ? 'Blueprint Saved' : 'Save Blueprint'}</span>
              </button>
            </div>

            <button
              onClick={handleExportMarkdown}
              className="flex items-center justify-center gap-2 bg-[#181924] hover:bg-[#2A2B3D] text-white px-5 py-2 rounded-xl text-xs font-mono font-bold transition-all shadow-subtle"
            >
              {copiedMarkdown ? <Check className="w-3.5 h-3.5 text-[#4FA89B]" /> : <Download className="w-3.5 h-3.5" />}
              <span>{copiedMarkdown ? 'Copied Dossier!' : 'Export Dossier (.md)'}</span>
            </button>
          </div>

          {/* Collapsible Constraints Box */}
          {showConstraints && (
            <div className="p-5 bg-[#F7F4EE] rounded-2xl border border-[#E5E0D6] space-y-4 animate-in fade-in duration-200">
              <div className="font-mono text-xs font-bold text-[#181924] uppercase tracking-wider">
                Tailor Synthesis to Project Target
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs font-mono">
                <div>
                  <label className="block text-[#8E90A2] mb-1.5 uppercase text-[10px]">Data Privacy Level</label>
                  <select
                    value={privacy}
                    onChange={(e) => {
                      const val = e.target.value as any;
                      setPrivacy(val);
                      if (onUpdateConstraints) onUpdateConstraints({ privacyLevel: val });
                    }}
                    className="w-full bg-white border border-[#E5E0D6] rounded-xl p-2.5 outline-none font-sans text-xs"
                  >
                    <option value="100% Offline / Self-Hosted">100% Offline / Self-Hosted</option>
                    <option value="Hybrid (Local + Cloud)">Hybrid (Local + Cloud)</option>
                    <option value="Cloud Native">Cloud Native</option>
                  </select>
                </div>

                <div>
                  <label className="block text-[#8E90A2] mb-1.5 uppercase text-[10px]">Project Scale</label>
                  <select
                    value={scale}
                    onChange={(e) => {
                      const val = e.target.value as any;
                      setScale(val);
                      if (onUpdateConstraints) onUpdateConstraints({ projectScale: val });
                    }}
                    className="w-full bg-white border border-[#E5E0D6] rounded-xl p-2.5 outline-none font-sans text-xs"
                  >
                    <option value="MVP (1-1,000 users)">MVP (1-1,000 users)</option>
                    <option value="Growth (10,000 users)">Growth (10,000 users)</option>
                    <option value="Scale (100,000+ users)">Scale (100,000+ users)</option>
                  </select>
                </div>

                <div>
                  <label className="block text-[#8E90A2] mb-1.5 uppercase text-[10px]">Target Platform</label>
                  <select
                    value={platform}
                    onChange={(e) => {
                      const val = e.target.value as any;
                      setPlatform(val);
                      if (onUpdateConstraints) onUpdateConstraints({ targetPlatform: val });
                    }}
                    className="w-full bg-white border border-[#E5E0D6] rounded-xl p-2.5 outline-none font-sans text-xs"
                  >
                    <option value="Web Application">Web Application</option>
                    <option value="Mobile App (iOS/Android)">Mobile App (iOS/Android)</option>
                    <option value="Cross-Platform Fullstack">Cross-Platform Fullstack</option>
                  </select>
                </div>
              </div>
            </div>
          )}

        </div>
      </SlideUp>

      {/* Sub-Navigation Tabs */}
      <div className="flex items-center gap-2 overflow-x-auto pb-1 border-b border-[#E5E0D6]">
        {[
          { id: 'compare_solutions', label: `⚖️ Compare Related Solutions (${activeSolution.relatedSolutions?.length || 0})`, icon: Scale },
          { id: 'suggestions', label: `💡 AI Recommendations (${suggestionsList.length})`, icon: Lightbulb },
          { id: 'architecture', label: 'Architecture Blueprint', icon: Layers },
          { id: 'stack', label: `Open Source Stack (${activeSolution.openSourceStack?.length || 0})`, icon: GitFork },
          { id: 'roadmap', label: 'Step-by-Step Roadmap', icon: Calendar },
          { id: 'starter_code', label: 'Starter Code & Boilerplate', icon: Code2 },
          { id: 'tradeoffs', label: 'Tradeoffs & Cost Comparison', icon: TrendingDown },
        ].map(tab => {
          const Icon = tab.icon;
          const isActive = activeTab === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`
                flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-mono font-bold transition-all whitespace-nowrap
                ${isActive 
                  ? 'bg-white text-[#181924] border border-[#E5E0D6] shadow-sm' 
                  : 'text-[#555768] hover:text-[#181924] hover:bg-white/50'
                }
              `}
              style={isActive ? { borderColor: 'var(--color-coral)' } : {}}
            >
              <Icon className="w-3.5 h-3.5" style={isActive ? { color: 'var(--color-coral)' } : {}} />
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>

      {/* ── TAB 0: COMPARE RELATED SOLUTIONS (SIDE-BY-SIDE MATRIX) ── */}
      {activeTab === 'compare_solutions' && (
        <SlideUp delay={0.05}>
          <SolutionComparisonMatrix 
            relatedSolutions={activeSolution.relatedSolutions || []}
            activeApproachId={activeSolution.activeApproachId || 'approach_fullstack_oss'}
            onSelectApproach={handleSelectApproach}
            queryTitle={activeSolution.queryTitle || activeSolution.title || ''}
          />
        </SlideUp>
      )}

      {/* ── TAB 1: AI RECOMMENDATIONS & SUGGESTIONS ── */}
      {activeTab === 'suggestions' && (
        <SlideUp delay={0.05}>
          <div className="space-y-6">
            
            {/* Action Bar with Filter Pills & "Generate More" Button */}
            <div className="bg-white rounded-3xl border border-[#E5E0D6] p-6 shadow-subtle flex flex-col md:flex-row md:items-center justify-between gap-4">
              <div className="flex items-center gap-2 overflow-x-auto pb-1">
                {[
                  { id: 'all', label: 'All Suggestions' },
                  { id: 'quick_win', label: '⚡ MVP Quick Wins' },
                  { id: 'differentiation', label: '🛡️ Competitive Moats' },
                  { id: 'open_source', label: '📦 Open Source Boost' },
                  { id: 'growth', label: '📈 Growth & Virality' },
                  { id: 'monetization', label: '💰 Monetization' },
                ].map(f => (
                  <button
                    key={f.id}
                    onClick={() => setSelectedCategoryFilter(f.id)}
                    className={`px-3 py-1.5 rounded-xl text-xs font-mono font-bold transition-all whitespace-nowrap ${
                      selectedCategoryFilter === f.id
                        ? 'bg-[#181924] text-white'
                        : 'bg-[#F7F4EE] text-[#555768] hover:bg-[#E5E0D6] border border-[#E5E0D6]'
                    }`}
                  >
                    {f.label}
                  </button>
                ))}
              </div>

              <button
                onClick={handleGenerateMoreSuggestions}
                className="flex items-center gap-2 bg-[#6875E8] hover:bg-[#5563D6] text-white px-4 py-2 rounded-xl text-xs font-mono font-bold transition-all shadow-subtle shrink-0"
              >
                <Plus className="w-3.5 h-3.5" />
                <span>GENERATE MORE SUGGESTIONS</span>
              </button>
            </div>

            {/* Suggestions Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              {filteredSuggestions.map((sug) => {
                const isCopied = copiedSuggestionId === sug.id;
                return (
                  <div
                    key={sug.id}
                    className="bg-white rounded-3xl border border-[#E5E0D6] p-6 shadow-subtle space-y-4 flex flex-col justify-between hover:border-[#181924]/30 transition-all group"
                  >
                    <div className="space-y-3">
                      {/* Top Badges */}
                      <div className="flex items-center justify-between">
                        <span 
                          className="text-[10px] font-mono font-bold uppercase px-2.5 py-1 rounded-lg"
                          style={{ 
                            background: `${sug.badgeColor}15`, 
                            color: sug.badgeColor,
                            border: `1px solid ${sug.badgeColor}30` 
                          }}
                        >
                          {sug.categoryLabel}
                        </span>

                        <div className="flex items-center gap-2 text-[10px] font-mono font-bold">
                          <span className="text-[#4FA89B]">{sug.impact}</span>
                          <span className="text-[#E5E0D6]">•</span>
                          <span className="text-[#8E90A2]">{sug.effort}</span>
                        </div>
                      </div>

                      {/* Title */}
                      <h3 className="font-serif text-xl font-bold text-[#181924] group-hover:text-[#6875E8] transition-colors">
                        {sug.title}
                      </h3>

                      {/* Description */}
                      <p className="text-xs text-[#555768] leading-relaxed">
                        {sug.description}
                      </p>

                      {/* Actionable Step Box */}
                      <div className="p-3.5 bg-[#F7F4EE] rounded-2xl border border-[#E5E0D6] text-xs space-y-1">
                        <div className="flex items-center gap-1.5 text-[#181924] font-mono font-bold text-[10px] uppercase">
                          <ArrowRight className="w-3 h-3 text-[#6875E8]" />
                          <span>Actionable Implementation Step:</span>
                        </div>
                        <p className="text-[#555768] pl-4">{sug.actionableStep}</p>
                      </div>
                    </div>

                    {/* Copy Suggestion */}
                    <div className="pt-3 border-t border-[#E5E0D6] flex justify-end">
                      <button
                        onClick={() => handleCopySuggestion(sug)}
                        className="flex items-center gap-1.5 text-[11px] font-mono text-[#8E90A2] hover:text-[#181924] transition-colors"
                      >
                        {isCopied ? <Check className="w-3.5 h-3.5 text-[#4FA89B]" /> : <Copy className="w-3.5 h-3.5" />}
                        <span>{isCopied ? 'Copied' : 'Copy Suggestion'}</span>
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>

          </div>
        </SlideUp>
      )}

      {/* ── TAB 2: ARCHITECTURE LAYERS ── */}
      {activeTab === 'architecture' && (
        <SlideUp delay={0.05}>
          <div className="space-y-4">
            {(activeSolution.architecture || []).map((layer: any, idx: number) => (
              <div 
                key={idx}
                className="bg-white rounded-2xl border border-[#E5E0D6] p-6 shadow-subtle flex flex-col md:flex-row md:items-center justify-between gap-4 hover:border-[#181924]/30 transition-all"
              >
                <div className="space-y-1 max-w-2xl">
                  <div className="flex items-center gap-2">
                    <span 
                      className="text-[10px] font-mono font-bold uppercase px-2 py-0.5 rounded"
                      style={{ background: `${layer.badgeColor || '#6875E8'}15`, color: layer.badgeColor || '#6875E8' }}
                    >
                      {layer.layer}
                    </span>
                    <h4 className="font-serif text-lg font-bold text-[#181924]">
                      {layer.component || layer.name}
                    </h4>
                  </div>
                  <p className="text-xs text-[#555768] leading-relaxed">
                    {layer.role || layer.description}
                  </p>
                </div>

                <div className="bg-[#F7F4EE] px-4 py-3 rounded-xl border border-[#E5E0D6] font-mono text-xs text-[#181924] font-bold shrink-0 self-start md:self-auto">
                  {layer.technology || (layer.components && layer.components.join(', '))}
                </div>
              </div>
            ))}
          </div>
        </SlideUp>
      )}

      {/* ── TAB 3: OPEN SOURCE STACK ── */}
      {activeTab === 'stack' && (
        <SlideUp delay={0.05}>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {(activeSolution.openSourceStack || []).map((tool: any, idx: number) => (
              <div 
                key={tool.id || idx}
                className="bg-white rounded-2xl border border-[#E5E0D6] p-6 shadow-subtle flex flex-col justify-between space-y-4 hover:border-[#181924]/30 transition-all"
              >
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <h4 className="font-serif text-lg font-bold text-[#181924]">
                      {tool.name || tool.toolName}
                    </h4>
                    {tool.stars && (
                      <span className="text-xs font-mono font-bold text-[#E8B653] bg-[#E8B653]/10 px-2 py-0.5 rounded">
                        ★ {tool.stars}
                      </span>
                    )}
                  </div>
                  <p className="text-xs text-[#555768] leading-relaxed line-clamp-3">
                    {tool.description || tool.reason}
                  </p>
                </div>

                <div className="space-y-3 pt-2 border-t border-[#E5E0D6]">
                  {tool.installCommand && (
                    <div className="p-2.5 bg-[#F7F4EE] rounded-lg font-mono text-[11px] text-[#181924] truncate">
                      <code>{tool.installCommand}</code>
                    </div>
                  )}

                  <div className="flex items-center gap-2">
                    {(tool.githubUrl || tool.officialUrl) && (
                      <a
                        href={tool.githubUrl || tool.officialUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex-1 py-1.5 px-3 rounded-lg bg-[#181924] text-white font-mono text-xs font-bold flex items-center justify-center gap-1.5 hover:bg-[#2A2B3D] transition-all"
                      >
                        <span>Resource</span>
                        <ExternalLink className="w-3 h-3" />
                      </a>
                    )}

                    {(tool.websiteUrl || tool.officialUrl) && (
                      <a
                        href={tool.websiteUrl || tool.officialUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="py-1.5 px-3 rounded-lg bg-[#F7F4EE] text-[#181924] border border-[#E5E0D6] font-mono text-xs font-bold hover:bg-[#E5E0D6] transition-all"
                      >
                        Docs
                      </a>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </SlideUp>
      )}

      {/* ── TAB 4: STEP-BY-STEP ROADMAP ── */}
      {activeTab === 'roadmap' && (
        <SlideUp delay={0.05}>
          <div className="space-y-4">
            {(activeSolution.roadmap || []).map((phase: any, idx: number) => (
              <div 
                key={idx}
                className="bg-white rounded-2xl border border-[#E5E0D6] p-6 shadow-subtle space-y-4"
              >
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-[#E5E0D6] pb-3">
                  <div className="flex items-center gap-3">
                    <span className="w-7 h-7 rounded-full bg-[#181924] text-white font-mono font-bold text-xs flex items-center justify-center shrink-0">
                      0{idx + 1}
                    </span>
                    <div>
                      <h4 className="font-serif text-lg font-bold text-[#181924]">
                        {phase.title}
                      </h4>
                      <span className="text-[11px] font-mono text-[#8E90A2] uppercase font-bold">
                        {phase.phase || `Phase ${idx + 1}`}
                      </span>
                    </div>
                  </div>
                  <span className="text-xs font-mono font-bold px-3 py-1 rounded-full bg-[#4FA89B]/10 text-[#4FA89B] border border-[#4FA89B]/20 shrink-0">
                    EST: {phase.duration}
                  </span>
                </div>

                <div className="space-y-2 pl-2 sm:pl-10">
                  <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-[#8E90A2] block">
                    Execution Checklist:
                  </span>
                  <ul className="space-y-2 text-xs text-[#555768]">
                    {(phase.tasks || []).map((task: any, tIdx: number) => (
                      <li key={tIdx} className="flex items-start gap-2.5">
                        <span className="w-1.5 h-1.5 rounded-full bg-[#6875E8] mt-1.5 shrink-0" />
                        <span className="leading-relaxed">{typeof task === 'string' ? task : task?.title || ''}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="pl-2 sm:pl-10 pt-2">
                  <div className="p-3 bg-[#F7F4EE] rounded-xl border border-[#E5E0D6] flex items-center gap-2 text-xs font-mono">
                    <ShieldCheck className="w-4 h-4 text-[#4FA89B] shrink-0" />
                    <span className="text-[#181924] font-bold">Milestone Deliverable:</span>
                    <span className="text-[#555768]">{phase.deliverable || (phase.deliverables && phase.deliverables.join(', '))}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </SlideUp>
      )}

      {/* ── TAB 5: MULTI-LANGUAGE CODE SANDBOX ── */}
      {activeTab === 'starter_code' && (
        <SlideUp delay={0.05}>
          <MultiLangCodeSandbox 
            codeBundle={activeSolution.codeBundle}
            projectTitle={activeSolution.queryTitle || activeSolution.title || ''}
          />
        </SlideUp>
      )}

      {/* ── TAB 6: TRADEOFFS & PITFALLS ── */}
      {activeTab === 'tradeoffs' && (
        <SlideUp delay={0.05}>
          <div className="space-y-6">
            
            {/* Tradeoffs Table */}
            <div className="bg-white rounded-2xl border border-[#E5E0D6] p-6 shadow-subtle space-y-4">
              <div className="flex items-center justify-between border-b border-[#E5E0D6] pb-3">
                <h4 className="font-serif text-lg font-bold text-[#181924]">
                  Open Source vs Proprietary SaaS Comparison
                </h4>
                <Badge variant="purple">FINANCIAL & ARCHITECTURAL ADVANTAGE</Badge>
              </div>

              <div className="space-y-4">
                {(activeSolution.tradeoffs || []).map((item: any, idx: number) => (
                  <div key={idx} className="p-4 bg-[#F7F4EE] rounded-xl border border-[#E5E0D6] space-y-2.5">
                    <div className="flex items-center justify-between">
                      <span className="font-serif font-bold text-base text-[#181924]">
                        {item.aspect || item.dimension}
                      </span>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                      <div className="p-3 bg-white rounded-lg border border-[#E5E0D6] space-y-1">
                        <span className="font-mono font-bold text-[#4FA89B] text-[10px] uppercase block">
                          ✓ Recommended Approach
                        </span>
                        <p className="text-[#555768]">{item.openSourceAdvantage || item.optionA || item.recommendation}</p>
                      </div>

                      <div className="p-3 bg-white rounded-lg border border-[#E5E0D6] space-y-1">
                        <span className="font-mono font-bold text-[#E96B7A] text-[10px] uppercase block">
                          ✗ Alternative Option
                        </span>
                        <p className="text-[#555768]">{item.proprietaryAlternative || item.optionB || item.alternative}</p>
                      </div>
                    </div>

                    <div className="text-[11px] font-mono text-[#6875E8] pt-1">
                      <strong>Verdict:</strong> {item.recommendation || item.verdict}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Pitfalls & Mitigations */}
            <div className="bg-white rounded-2xl border border-[#E5E0D6] p-6 shadow-subtle space-y-4">
              <div className="flex items-center gap-2 border-b border-[#E5E0D6] pb-3">
                <AlertTriangle className="w-4 h-4 text-[#E8B653]" />
                <h4 className="font-serif text-lg font-bold text-[#181924]">
                  Proactive Pitfalls & Engineering Mitigations
                </h4>
              </div>

              <div className="space-y-3">
                {(activeSolution.pitfallsAndMitigations || []).map((item: any, idx: number) => (
                  <div key={idx} className="p-4 rounded-xl border border-[#E5E0D6] bg-[#F7F4EE] flex items-start gap-3">
                    <span 
                      className={`text-[9px] font-mono font-bold uppercase px-2 py-0.5 rounded-md shrink-0 mt-0.5 ${
                        item.severity === 'high' ? 'bg-[#E96B7A]/10 text-[#E96B7A] border border-[#E96B7A]/30' :
                        item.severity === 'medium' ? 'bg-[#E8B653]/10 text-[#E8B653] border border-[#E8B653]/30' :
                        'bg-[#4FA89B]/10 text-[#4FA89B] border border-[#4FA89B]/30'
                      }`}
                    >
                      {item.severity || 'Notice'}
                    </span>
                    <div className="space-y-1 text-xs">
                      <div className="font-bold text-[#181924]">{item.risk || item.pitfall}</div>
                      <div className="text-[#555768]"><strong className="text-[#4FA89B]">Fix:</strong> {item.mitigation}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

          </div>
        </SlideUp>
      )}

    </div>
  );
};
